spring.application.name=lms
server.port=9545
#Database settings
spring.datasource.url=jdbc:h2:file:C:/Users/Admin/Documents/Projects WS/LMS/LMSstore;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.initialization-mode=always
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=embedded
spring.sql.init.schema-locations=optional:classpath:sql/schema.sql
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true